### ISSUE TITLE
能否实时的修改每个时间段的歌词

### ISSUE THREAD

**Issue by zhangya5847** [yiyizym/lrc_editor#1]
上传歌词之后，打过标签之后，能够直接在页面上修改每个时间端的歌词，而不需要再打开上传歌词在文件里面修改，比较麻烦。

**Comment by yiyizym** [comment]
这个功能之前有考虑做的，可能需要一点时间。

感谢反馈～我还以为这玩意儿只有我自己用呢

**Comment by yiyizym** [comment]
已经实现这个功能了
