### ISSUE TITLE
打tag的顺序问题

### ISSUE THREAD

**Issue by zhangya5847** [yiyizym/lrc_editor#2]
打过Tag，重新播放之后，打的Tag是在直接打的Tag之后，会有顺序问题。

**Comment by yiyizym** [comment]
不是很懂这个问题， “打的Tag是在直接打的Tag之后”是什么意思呢？

**Comment by zhangya5847** [comment]
我的意思是，在播放之后，打了部分Tag，然后再重新打Tag，打的Tag不是重新开始打Tag，而是打在了之前打的Tag之后，不知道我有没有说明白。

**Comment by yiyizym** [comment]
好，我今晚复现一下

**Comment by yiyizym** [comment]
应该修复了。不过要注意点击“打 TAG”会打在灰色底色的栏目上。

**Comment by zhangya5847** [comment]
OK了，谢谢！
